// Generated by Wrangler on Wed Apr 03 2024 05:56:35 GMT+0900 (Japan Standard Time)
// by running `wrangler types`

// biome-ignore lint/correctness/noUnusedVariables: .d.tsファイルのため
interface Env {
  // biome-ignore lint/style/useNamingConvention: <explanation>
  my_remix_app_2: KVNamespace;
  // biome-ignore lint/style/useNamingConvention: <explanation>
  DB: D1Database;
}
