name: Deploy preview

on:
  push:
    branches:
      - preview

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Setup Bun
        uses: oven-sh/setup-bun@d3603274aca5625baad52ec06108517a089cdd00 # v1
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Apply migrations
        run: bun wrangler d1 migrations apply my_remix_app_2 --preview --remote
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - name: Deploy
        run: bun wrangler pages deploy ./build/client
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
